import { ReactNode } from "react";

interface AISectionProps {
  label: string;
  content?: string;
  children?: ReactNode;
}

const AISection = ({ label, content, children }: AISectionProps) => {
  return (
    <div className="ai-section">
      <div className="ai-section-label">{label}</div>
      {content && (
        <p
          className="text-sm text-foreground leading-relaxed"
          dangerouslySetInnerHTML={{
            __html: content
              .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>")
              .replace(/\*([^*]+)\*/g, "<em>$1</em>"),
          }}
        />
      )}
      {children}
      <div className="ai-attribution">Generated by Claude</div>
    </div>
  );
};

export default AISection;
