import { ReactNode } from "react";

interface AISectionProps {
  label: string;
  content?: string;
  children?: ReactNode;
}

const AISection = ({ label, content, children }: AISectionProps) => {
  return (
    <div className="ai-section">
      <div className="ai-section-label">{label}</div>
      {content && <p className="text-sm text-foreground leading-relaxed">{content}</p>}
      {children}
      <div className="ai-attribution">Generated by Claude</div>
    </div>
  );
};

export default AISection;
